language: node_js

env:
    # HEROKU_API_KEY
    - secure: "gRgDGxI8MdHIq7tbOCDcaSndeFZYH0pFJMXeAWkcb91NebeE57B8PKmtbuNv/cceKP38iGYAk7Abp5lF3Pipqwbn1IrX763wOUbMgodqFPhnKhAKMkZygce0R02CqgljBXWsqcYFHov18Y2byMXuAxy1y7YF+Nu8YaeC6DUVqzzk2uml9PeTJjYII+JifrpwZmC0jJu349Mt5b1ujxU2uZjLvTcCx3ZwE3ePl9xEdBzYDbZ6u3Ffctwj1AzQPOyjjSZ/BBuBiKZ1bh4M/F9ucGTbx9N4r+uTP4NRONXmtOxIN1Fo05qDZHsx/pnv5gpWePbD2WFylURvUWImlnRtIoNpG9dqRgs80Xa7KoBqWHSjWuDuYWja9bPmyCj91GQniczTLdxJ9D7wg+FdpNg6T96lnr0OqqdLGvOz7zodJF287rcqDvKiX1/tyKl+pENfoyHF561ulnQCRo+4XAC4iXJDaVg3XLbANseGZdZ8zzBYXAkGTlR9yLGxQE7e+y16WoFiwrL8cEtnB8QZlWPd0MEri2jgLKPtzbmyXE/RtzwgQdEK6tV3ou1uChH3KO/4pI+h7S/OsyKnm5hecIFNNHNXj2zkT8S7ET9Htz7HimcrOHETdBniKO6Ist8HXjlynM6Bmpcq4qvCC6I2uD9pUN9V/PAsYNtWZgsCfr+KtZs="

script:
    - yarn run build

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app:
        master: js-react-weather-app
    skip_cleanup: true
